### ISSUE TITLE
error cannot find module 'csv-parser'

### ISSUE THREAD

**Issue by nurlanov-zh** [JosephAnson/convert-myheritage-to-23andme#1]
### Describe the bug

Thanks for the converter! 
Since it requires scv parser, it throws the above error. So installing csv parser by `npm install csv` or `npm install csv-parse` solves the issue.

### Reproduction

running `npm run convert`

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 187.97 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 15.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/josephanson/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/josephanson/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JosephAnson** [comment]
Did you make sure to install the packages via the package.json? By running npm install it would install `csv-parser` for you.  

You can see here it's listed as a dependency: https://github.com/JosephAnson/convert-myheritage-to-23andme/blob/main/package.json

Thanks for taking the time to submit an issue
